// flow-typed signature: 5501934aa1671ca4c6cb083e98a9521f
// flow-typed version: <<STUB>>/babel-preset-stage-0_v6.5.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-stage-0'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-stage-0' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-stage-0/index' {
  declare module.exports: $Exports<'babel-preset-stage-0'>;
}
declare module 'babel-preset-stage-0/index.js' {
  declare module.exports: $Exports<'babel-preset-stage-0'>;
}
