// flow-typed signature: 7c01ac8fc679b8fb89406e8322ee23d7
// flow-typed version: <<STUB>>/conventional-recommended-bump_v0.3.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'conventional-recommended-bump'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'conventional-recommended-bump' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'conventional-recommended-bump/cli' {
  declare module.exports: any;
}

declare module 'conventional-recommended-bump/presets/angular' {
  declare module.exports: any;
}

declare module 'conventional-recommended-bump/test/angular' {
  declare module.exports: any;
}

declare module 'conventional-recommended-bump/test/prepare' {
  declare module.exports: any;
}

declare module 'conventional-recommended-bump/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'conventional-recommended-bump/cli.js' {
  declare module.exports: $Exports<'conventional-recommended-bump/cli'>;
}
declare module 'conventional-recommended-bump/index' {
  declare module.exports: $Exports<'conventional-recommended-bump'>;
}
declare module 'conventional-recommended-bump/index.js' {
  declare module.exports: $Exports<'conventional-recommended-bump'>;
}
declare module 'conventional-recommended-bump/presets/angular.js' {
  declare module.exports: $Exports<'conventional-recommended-bump/presets/angular'>;
}
declare module 'conventional-recommended-bump/test/angular.js' {
  declare module.exports: $Exports<'conventional-recommended-bump/test/angular'>;
}
declare module 'conventional-recommended-bump/test/prepare.js' {
  declare module.exports: $Exports<'conventional-recommended-bump/test/prepare'>;
}
declare module 'conventional-recommended-bump/test/test.js' {
  declare module.exports: $Exports<'conventional-recommended-bump/test/test'>;
}
