// flow-typed signature: 3e2ae441f07a5ee3532ef3c3be89bf76
// flow-typed version: <<STUB>>/react-sticky_vgit://github.com/susielu/react-sticky.git#23141c78f7e0501dc6a7b31b9e33db2e367b185f/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-sticky'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-sticky' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-sticky/dist/react-sticky' {
  declare module.exports: any;
}

declare module 'react-sticky/dist/react-sticky.min' {
  declare module.exports: any;
}

declare module 'react-sticky/lib/channel' {
  declare module.exports: any;
}

declare module 'react-sticky/lib/container' {
  declare module.exports: any;
}

declare module 'react-sticky/lib/index' {
  declare module.exports: any;
}

declare module 'react-sticky/lib/sticky' {
  declare module.exports: any;
}

declare module 'react-sticky/src/channel' {
  declare module.exports: any;
}

declare module 'react-sticky/src/container' {
  declare module.exports: any;
}

declare module 'react-sticky/src/index' {
  declare module.exports: any;
}

declare module 'react-sticky/src/sticky' {
  declare module.exports: any;
}

declare module 'react-sticky/test/setup' {
  declare module.exports: any;
}

declare module 'react-sticky/test/unit/channel' {
  declare module.exports: any;
}

declare module 'react-sticky/test/unit/container' {
  declare module.exports: any;
}

declare module 'react-sticky/test/unit/sticky' {
  declare module.exports: any;
}

declare module 'react-sticky/test/utils' {
  declare module.exports: any;
}

declare module 'react-sticky/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-sticky/dist/react-sticky.js' {
  declare module.exports: $Exports<'react-sticky/dist/react-sticky'>;
}
declare module 'react-sticky/dist/react-sticky.min.js' {
  declare module.exports: $Exports<'react-sticky/dist/react-sticky.min'>;
}
declare module 'react-sticky/lib/channel.js' {
  declare module.exports: $Exports<'react-sticky/lib/channel'>;
}
declare module 'react-sticky/lib/container.js' {
  declare module.exports: $Exports<'react-sticky/lib/container'>;
}
declare module 'react-sticky/lib/index.js' {
  declare module.exports: $Exports<'react-sticky/lib/index'>;
}
declare module 'react-sticky/lib/sticky.js' {
  declare module.exports: $Exports<'react-sticky/lib/sticky'>;
}
declare module 'react-sticky/src/channel.js' {
  declare module.exports: $Exports<'react-sticky/src/channel'>;
}
declare module 'react-sticky/src/container.js' {
  declare module.exports: $Exports<'react-sticky/src/container'>;
}
declare module 'react-sticky/src/index.js' {
  declare module.exports: $Exports<'react-sticky/src/index'>;
}
declare module 'react-sticky/src/sticky.js' {
  declare module.exports: $Exports<'react-sticky/src/sticky'>;
}
declare module 'react-sticky/test/setup.js' {
  declare module.exports: $Exports<'react-sticky/test/setup'>;
}
declare module 'react-sticky/test/unit/channel.js' {
  declare module.exports: $Exports<'react-sticky/test/unit/channel'>;
}
declare module 'react-sticky/test/unit/container.js' {
  declare module.exports: $Exports<'react-sticky/test/unit/container'>;
}
declare module 'react-sticky/test/unit/sticky.js' {
  declare module.exports: $Exports<'react-sticky/test/unit/sticky'>;
}
declare module 'react-sticky/test/utils.js' {
  declare module.exports: $Exports<'react-sticky/test/utils'>;
}
declare module 'react-sticky/webpack.config.js' {
  declare module.exports: $Exports<'react-sticky/webpack.config'>;
}
