// flow-typed signature: 7ce17ff184c8b4501ee2cdc45484b11b
// flow-typed version: <<STUB>>/react-prism_v4.3.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-prism'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-prism' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-prism/lib/components/PrismCode' {
  declare module.exports: any;
}

declare module 'react-prism/lib/components/PrismCode.test' {
  declare module.exports: any;
}

declare module 'react-prism/lib/index' {
  declare module.exports: any;
}

declare module 'react-prism/lib/index.test' {
  declare module.exports: any;
}

declare module 'react-prism/src/components/PrismCode' {
  declare module.exports: any;
}

declare module 'react-prism/src/components/PrismCode.test' {
  declare module.exports: any;
}

declare module 'react-prism/src/index' {
  declare module.exports: any;
}

declare module 'react-prism/src/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-prism/lib/components/PrismCode.js' {
  declare module.exports: $Exports<'react-prism/lib/components/PrismCode'>;
}
declare module 'react-prism/lib/components/PrismCode.test.js' {
  declare module.exports: $Exports<'react-prism/lib/components/PrismCode.test'>;
}
declare module 'react-prism/lib/index.js' {
  declare module.exports: $Exports<'react-prism/lib/index'>;
}
declare module 'react-prism/lib/index.test.js' {
  declare module.exports: $Exports<'react-prism/lib/index.test'>;
}
declare module 'react-prism/src/components/PrismCode.js' {
  declare module.exports: $Exports<'react-prism/src/components/PrismCode'>;
}
declare module 'react-prism/src/components/PrismCode.test.js' {
  declare module.exports: $Exports<'react-prism/src/components/PrismCode.test'>;
}
declare module 'react-prism/src/index.js' {
  declare module.exports: $Exports<'react-prism/src/index'>;
}
declare module 'react-prism/src/index.test.js' {
  declare module.exports: $Exports<'react-prism/src/index.test'>;
}
