// flow-typed signature: da8e62e5478c61f1a929dbd55953bc6b
// flow-typed version: <<STUB>>/uglifyify_v4.0.4/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uglifyify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uglifyify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uglifyify/test/fixture' {
  declare module.exports: any;
}

declare module 'uglifyify/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uglifyify/index' {
  declare module.exports: $Exports<'uglifyify'>;
}
declare module 'uglifyify/index.js' {
  declare module.exports: $Exports<'uglifyify'>;
}
declare module 'uglifyify/test/fixture.js' {
  declare module.exports: $Exports<'uglifyify/test/fixture'>;
}
declare module 'uglifyify/test/index.js' {
  declare module.exports: $Exports<'uglifyify/test/index'>;
}
