// flow-typed signature: 939d4e3bb1e6eea76da92247eeda8efc
// flow-typed version: <<STUB>>/viz-annotation_v0.0.1-3/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'viz-annotation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'viz-annotation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'viz-annotation/lib/Builder' {
  declare module.exports: any;
}

declare module 'viz-annotation/lib/Connector/end-arrow' {
  declare module.exports: any;
}

declare module 'viz-annotation/lib/Connector/end-dot' {
  declare module.exports: any;
}

declare module 'viz-annotation/lib/Connector/type-curve' {
  declare module.exports: any;
}

declare module 'viz-annotation/lib/Connector/type-elbow' {
  declare module.exports: any;
}

declare module 'viz-annotation/lib/Connector/type-line' {
  declare module.exports: any;
}

declare module 'viz-annotation/lib/index' {
  declare module.exports: any;
}

declare module 'viz-annotation/lib/Note/alignment' {
  declare module.exports: any;
}

declare module 'viz-annotation/lib/Note/lineType-horizontal' {
  declare module.exports: any;
}

declare module 'viz-annotation/lib/Note/lineType-vertical' {
  declare module.exports: any;
}

declare module 'viz-annotation/lib/Subject/badge' {
  declare module.exports: any;
}

declare module 'viz-annotation/lib/Subject/bracket' {
  declare module.exports: any;
}

declare module 'viz-annotation/lib/Subject/circle' {
  declare module.exports: any;
}

declare module 'viz-annotation/lib/Subject/rect' {
  declare module.exports: any;
}

declare module 'viz-annotation/lib/Subject/threshold' {
  declare module.exports: any;
}

// Filename aliases
declare module 'viz-annotation/lib/Builder.js' {
  declare module.exports: $Exports<'viz-annotation/lib/Builder'>;
}
declare module 'viz-annotation/lib/Connector/end-arrow.js' {
  declare module.exports: $Exports<'viz-annotation/lib/Connector/end-arrow'>;
}
declare module 'viz-annotation/lib/Connector/end-dot.js' {
  declare module.exports: $Exports<'viz-annotation/lib/Connector/end-dot'>;
}
declare module 'viz-annotation/lib/Connector/type-curve.js' {
  declare module.exports: $Exports<'viz-annotation/lib/Connector/type-curve'>;
}
declare module 'viz-annotation/lib/Connector/type-elbow.js' {
  declare module.exports: $Exports<'viz-annotation/lib/Connector/type-elbow'>;
}
declare module 'viz-annotation/lib/Connector/type-line.js' {
  declare module.exports: $Exports<'viz-annotation/lib/Connector/type-line'>;
}
declare module 'viz-annotation/lib/index.js' {
  declare module.exports: $Exports<'viz-annotation/lib/index'>;
}
declare module 'viz-annotation/lib/Note/alignment.js' {
  declare module.exports: $Exports<'viz-annotation/lib/Note/alignment'>;
}
declare module 'viz-annotation/lib/Note/lineType-horizontal.js' {
  declare module.exports: $Exports<'viz-annotation/lib/Note/lineType-horizontal'>;
}
declare module 'viz-annotation/lib/Note/lineType-vertical.js' {
  declare module.exports: $Exports<'viz-annotation/lib/Note/lineType-vertical'>;
}
declare module 'viz-annotation/lib/Subject/badge.js' {
  declare module.exports: $Exports<'viz-annotation/lib/Subject/badge'>;
}
declare module 'viz-annotation/lib/Subject/bracket.js' {
  declare module.exports: $Exports<'viz-annotation/lib/Subject/bracket'>;
}
declare module 'viz-annotation/lib/Subject/circle.js' {
  declare module.exports: $Exports<'viz-annotation/lib/Subject/circle'>;
}
declare module 'viz-annotation/lib/Subject/rect.js' {
  declare module.exports: $Exports<'viz-annotation/lib/Subject/rect'>;
}
declare module 'viz-annotation/lib/Subject/threshold.js' {
  declare module.exports: $Exports<'viz-annotation/lib/Subject/threshold'>;
}
